# -*- coding: utf-8 -*-
"""Newspaper1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PkyPF0RPBpTONpoER1Uqa4I14Ny2LvX0
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("IndianNewsPaper1.csv")

df

df.describe()

df.info()

df.shape

df.isnull().sum()

df.isnull().sum().sum()

df['Interval of publication'].fillna('Daily', inplace = True)
df['Format'].fillna('Broadsheet', inplace = True)
df['Location'].fillna(method = 'pad', inplace = True)
df['Founded'].fillna(df['Founded'].mean().astype(int), inplace = True)

df.tail(20)

df.isnull().sum().sum()

import numpy as np
import matplotlib.pyplot as plt

# X axis parameter:
xaxis = df['Founded']
#np.array([1930, 2025])

# Y axis parameter:
#yaxis = np.array([1930, 2025])
yaxis = df['Founded']
plt.title('1931 From 2020')
plt.xlabel('Year')
plt.ylabel('Year')

plt.scatter(xaxis, yaxis)
plt.show()