# -*- coding: utf-8 -*-
"""Newspaper1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PkyPF0RPBpTONpoER1Uqa4I14Ny2LvX0
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("IndianNewsPaper1.csv")

df

df.head(20)

df.tail()

df.shape

df.dtypes

df.columns

df.info()

df.duplicated().sum()

df.describe()

df.isnull().sum()

df.isnull().sum().sum()

df['Interval of publication'].fillna('Daily', inplace = True)
df['Format'].fillna('Broadsheet', inplace = True)
df['Location'].fillna(method = 'pad', inplace = True)
df['Founded'].fillna(df['Founded'].mean().astype(int), inplace = True)

df.tail(20)

df.isnull().sum().sum()

import numpy as np
import matplotlib.pyplot as plt

# X axis parameter:
xaxis = df['Founded']


# Y axis parameter:
yaxis = df['Founded']

plt.title('1955 From 2020')
plt.xlim(1955, 2025)
plt.ylim(1955, 2025)
plt.xlabel('Year')
plt.ylabel('Year')

plt.scatter(xaxis, yaxis)
plt.grid()
plt.show()

